apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: docker.io/wolvecode/reverseproxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080